### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by davisem** [stjude/fqlib#2]
```
$ pip3 install fqlib
$ fqlint
Traceback (most recent call last):
  File "/usr/local/bin/fqlint", line 7, in <module>
    from fqlib import PairedFastQFiles, SingleReadValidationError, PairedReadValidationError
  File "/Users/edavis5/workspace/fqlib/fqlib/__init__.py", line 2, in <module>
    from .fastq import *
ModuleNotFoundError: No module named 'fqlib.fastq'
```

**Comment by claymcleod** [comment]
I can't reproduce:

```
~/Developer via 🅒 python-3.6.4
➜ pip install fqlib --no-cache
Collecting fqlib
  Downloading fqlib-1.0.1.tar.gz
Installing collected packages: fqlib
  Running setup.py install for fqlib ... done
Successfully installed fqlib-1.0.1
(python-3.6.4)
~/Developer via 🅒 python-3.6.4
➜ fqlint
usage: fqlint [-h] [--lint-mode {report,error}] [-s {minimum,low,high}]
              [-p {minimum,low,high}]
              [--stop-after-n-reads STOP_AFTER_N_READS]
              [--print-every-n-reads PRINT_EVERY_N_READS] [-q]
              read_one_file read_two_file
fqlint: error: the following arguments are required: read_one_file, read_two_file```

**Comment by davisem** [comment]
I only get it when I call `fqlint` from the `fqlib` dir. Strange.

**Comment by claymcleod** [comment]
Yeah, this is a byproduct of how python resolves modules, but not a bug.

**Comment by davisem** [comment]
Haven't encountered this one before.
