### ISSUE TITLE
Read name should exclude or ignore "the member of a pair"

### ISSUE THREAD

**Issue by adamdingliang** [stjude/fqlib#8]
See fastq file format:
https://en.wikipedia.org/wiki/FASTQ_format

```(py36) [lding@L170687 fqlib]$ ./bin/fqlint -s high ./example/03_duplicate_reads/duplicate_in_R1/R1.fastq ./example/03_duplicate_reads/duplicate_in_R1/R2.fastq
INFO : Single Read Validators: 4
DEBUG:   - S001 => PluslineValidator
DEBUG:   - S002 => AlphabetValidator
DEBUG:   - S003 => ReadnameValidator
DEBUG:   - S004 => CompleteReadValidator
INFO : Paired Read Validators: 1
DEBUG:   - P001 => PairedReadnameValidator
INFO : Started reading from files...
Traceback (most recent call last):
  File "./bin/fqlint", line 91, in <module>
    for readno, (read_r1, read_r2) in enumerate(pair, 1):
  File "fqlib/fastq.pyx", line 245, in fqlib.fastq.PairedFastQFiles.__next__
    result = self.next_readpair()
  File "fqlib/fastq.pyx", line 271, in fqlib.fastq.PairedFastQFiles.next_readpair
    raise PairedReadValidationError(
fqlib.error.PairedReadValidationError: Read Pair Number: 0
Read 1
   - File: R1.fastq
   - Line Number: 0
   - Readname: b'@K00202:217:HTLHYBBXX:2:1101:2169:998 1:N:0:NTCATTCC'
Read 2
   - File: R2.fastq
   - Line Number: 0
   - Readname: b'@K00202:217:HTLHYBBXX:2:1101:2169:998 2:N:0:NTCATTCC'
---
Read names do not match.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/fqlint", line 96, in <module>
    break
TypeError: __exit__() takes exactly one argument (4 given)
```

**Comment by claymcleod** [comment]
@adamdingliang Is the proposed solution just to split on space and take the first part if the second part is present?

**Comment by adamdingliang** [comment]
Yes. Information after space are additional. It should not be considered as read name.

**Comment by adamdingliang** [comment]
I will fix this in my branch.
